name: Deployment

on:
  push:
    tags:
      - v*
  release:
    types:
      - published

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run EsLint
        run: npm run eslint

      - name: Run StyleLint
        run: npm run stylelint

      - name: Run PreDeploy
        run: npm run predeploy
        
      - name: Run Deploy
        run: npm run deploy
