name: Deployment

on:
  push:
    tags:
      - v*
  release:
    types:
      - published

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run Lint
        run: npm run lint

      - name: Run PreDeploy
        run: npm run predeploy
        
      - name: Run Deploy
        run: npm run deploy
