name: Main workflows

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug 

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run EsLint
        run: npm run eslint
        
      - name: Run StyleLint
        run: npm run stylelint

      - name: Run Build
        run: npm run build
